networks:
  prod:
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - prod

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_STRING=mongodb://mongo:27017/your_database_name
    depends_on:
      - mongo
    networks:
      - prod

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - prod

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - prod

volumes:
  mongo_data:
